/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_HW1CLIENT_H_
#define JSONRPC_CPP_STUB_HW1CLIENT_H_

#include <jsonrpccpp/client.h>

class hw1Client : public jsonrpc::Client
{
    public:
        hw1Client(jsonrpc::IClientConnector &conn, jsonrpc::clientVersion_t type = jsonrpc::JSONRPC_CLIENT_V2) : jsonrpc::Client(conn, type) {}

        Json::Value GetDistance(const std::string& action, const std::string& arguments, const std::string& class_id, const std::string& host_url, const std::string& object_id, const std::string& owner_vsID) 
        {
            Json::Value p;
            p["action"] = action;
            p["arguments"] = arguments;
            p["class_id"] = class_id;
            p["host_url"] = host_url;
            p["object_id"] = object_id;
            p["owner_vsID"] = owner_vsID;
            Json::Value result = this->CallMethod("GetDistance",p);
            if (result.isObject())
                return result;
            else
                throw jsonrpc::JsonRpcException(jsonrpc::Errors::ERROR_CLIENT_INVALID_RESPONSE, result.toStyledString());
        }
        Json::Value Conflict_of_Interest(const std::string& action, const std::string& arguments, const std::string& class_id, const std::string& host_url, const std::string& object_id, const std::string& owner_vsID) 
        {
            Json::Value p;
            p["action"] = action;
            p["arguments"] = arguments;
            p["class_id"] = class_id;
            p["host_url"] = host_url;
            p["object_id"] = object_id;
            p["owner_vsID"] = owner_vsID;
            Json::Value result = this->CallMethod("Conflict_of_Interest",p);
            if (result.isObject())
                return result;
            else
                throw jsonrpc::JsonRpcException(jsonrpc::Errors::ERROR_CLIENT_INVALID_RESPONSE, result.toStyledString());
        }
        Json::Value GetVsID(const std::string& action, const std::string& arguments, const std::string& class_id, const std::string& host_url, const std::string& object_id, const std::string& owner_vsID) 
        {
            Json::Value p;
            p["action"] = action;
            p["arguments"] = arguments;
            p["class_id"] = class_id;
            p["host_url"] = host_url;
            p["object_id"] = object_id;
            p["owner_vsID"] = owner_vsID;
            Json::Value result = this->CallMethod("GetVsID",p);
            if (result.isObject())
                return result;
            else
                throw jsonrpc::JsonRpcException(jsonrpc::Errors::ERROR_CLIENT_INVALID_RESPONSE, result.toStyledString());
        }
        Json::Value getName(const std::string& action, const std::string& arguments, const std::string& class_id, const std::string& host_url, const std::string& object_id, const std::string& owner_vsID) 
        {
            Json::Value p;
            p["action"] = action;
            p["arguments"] = arguments;
            p["class_id"] = class_id;
            p["host_url"] = host_url;
            p["object_id"] = object_id;
            p["owner_vsID"] = owner_vsID;
            Json::Value result = this->CallMethod("getName",p);
            if (result.isObject())
                return result;
            else
                throw jsonrpc::JsonRpcException(jsonrpc::Errors::ERROR_CLIENT_INVALID_RESPONSE, result.toStyledString());
        }
        Json::Value OperatorEqEq(const std::string& aPerson_class_id, const std::string& aPerson_host_url, const std::string& aPerson_object_id, const std::string& aPerson_owner_vsID, const std::string& action, const std::string& arguments, const std::string& class_id, const std::string& host_url, const std::string& object_id, const std::string& owner_vsID) 
        {
            Json::Value p;
            p["aPerson_class_id"] = aPerson_class_id;
            p["aPerson_host_url"] = aPerson_host_url;
            p["aPerson_object_id"] = aPerson_object_id;
            p["aPerson_owner_vsID"] = aPerson_owner_vsID;
            p["action"] = action;
            p["arguments"] = arguments;
            p["class_id"] = class_id;
            p["host_url"] = host_url;
            p["object_id"] = object_id;
            p["owner_vsID"] = owner_vsID;
            Json::Value result = this->CallMethod("OperatorEqEq",p);
            if (result.isObject())
                return result;
            else
                throw jsonrpc::JsonRpcException(jsonrpc::Errors::ERROR_CLIENT_INVALID_RESPONSE, result.toStyledString());
        }
};

#endif //JSONRPC_CPP_STUB_HW1CLIENT_H_
